language: node_js

node_js:
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"

notifications:
  email:
    recipients:
      - martin@pipedrive.com
      - kristo.kaiv@pipedrive.com
    on_success: change
    on_failure: change

sudo: false
